### ISSUE TITLE
The /ask command not working

### ISSUE THREAD

**Issue by sossienl** [jordenc/org.telegram.api.bot#2]
Might be missing a step here, but when I send "/ask hoe laat is het?" in telegram, I hear pronounce the question via the speaker , but no answer. Behaviour is similar to /say.

Other commands, like ping and /say and /help work fine

**Comment by jordenc** [comment]
I think you misunderstood the functionality of this function.

When you do "/ask hoe laat is het", Homey will be listening to what YOU say as answer. Then when finished listening, it should show you the answer in Telegram.

Not really useful, but you could potentially use it to have a conversation with someone in your house. I just added it because it was possible and easy to do.

Sadly, it is not possible for me as a developer to "conversate" directly to Homey, so asking Homey a question or giving it a command is not possible. For that, you could better use the Facebook Messenger integration that Athom built, which connects to Homey directly as if you were talking to Homey.
